FROM python:3.12-slim

WORKDIR /app
# Install gcc and git
RUN apt-get update -y && apt-get install -y gcc && apt-get install -y git

# Create a virtual environment
RUN python -m venv venv

# Ensure pip is up-to-date in the virtual environment
RUN ./venv/bin/pip install --upgrade pip

# Install dependencies in the virtual environment
COPY requirements.txt /app/
RUN ./venv/bin/pip install --no-cache-dir -r requirements.txt

# Copy the src folder and requirements
COPY src/ /app/src/
COPY config/ /app/config/

# Ensure the script runs using the virtual environment's Python
ENTRYPOINT ["./venv/bin/python", "/app/src/runner.py"]

# Optionally, you can use CMD for default arguments (if any)
CMD []